services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=Europe/Bucharest
      - TZ=Europe/Bucharest
      - APIFY_API_TOKEN=${APIFY_API_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  n8n_data:
    driver: local
